### ISSUE TITLE
EzChat Not working

### ISSUE THREAD

**Issue by aerothan** [john01dav/SQLPermsIssues#2] opened 2015-04-09 12:52 UTC
http://pastebin.com/eU82C7XE

Got my log in the pastebin above, thanks for the help in advance!

[07:46:15] [Server thread/ERROR]: Could not load 'plugins\EzChat.jar' in folder 'plugins'

**Comment by john01dav** [comment] 2015-04-09 21:25
Try running with Oracle JDK/JRE 7 or OpenJDK 8.

**Comment by john01dav** [comment] 2015-04-11 00:36
Also, please fix the other errors in your setup (ie. the errors in permissions.yml).

**Comment by john01dav** [comment] 2015-04-11 05:15
It should be fixed in 1.0.1. Please open a new issue if it turns out not to be fixed.

**Comment by aerothan** [comment] 2015-04-13 03:18
same issue, http://pastebin.com/fS2vzAs4

**Comment by aerothan** [comment] 2015-04-13 03:20
and this is on the 1.0.1

**Comment by aerothan** [comment] 2015-04-14 03:47
Any Updates? Thanks.

**Comment by john01dav** [comment] 2015-04-14 08:35
The issue is currently in progress of being fixed. If you want me to prove it works for others, send me a PM on Spigot.

**Comment by aerothan** [comment] 2015-04-14 17:38
Is there a eta for the fix? It might work but doesnt help me if mine isnt working lol

**Comment by aerothan** [comment] 2015-04-15 12:57
http://pastebin.com/E9wj6nLw

**Comment by john01dav** [comment] 2015-04-15 21:38
There is no ETA at the current moment.

**Comment by aerothan** [comment] 2015-04-17 01:27
Any updates would really like to get this working

**Comment by john01dav** [comment] 2015-04-17 21:59
[I think I found a lead on what's up.](www.spigotmc.org/threads/spigot-premium-resources-changing-jar-files-why.61370) Once this lead solidifies, I'll fix this if this lead is truly what is causing the error. I can see why it would be too.

**Comment by john01dav** [comment] 2015-04-18 12:21
Ok, I've been talking to md_5 about this, it turns out that Spigot messes with Jar files uploaded and there messing is causing the errors -- which is why it didn't happen in my testing. If someone wants the original Jar file, then please PM me your Spigot email.

**Closed** 2015-04-18 12:21 UTC

**Comment by john01dav** [comment] 2015-04-19 14:57
md_5 told me that Spigot changed its messing-with algorithm, so it should be fixed now even for those who download from Spigot.
